name: MMGen
version: 4.0.0
main: kurosio.mmgen.MMGen
api-version: '1.13'
softdepend:
  - MythicMobs

commands:
  mmgen:
    description: Generate MythicMobs item YAML
    usage: /mmgen items create newid:<newMMID> [options:<option>] [acm:<acm>]

permissions:
  mmgen.use:
    description: Allows use of MMGen
    default: op